// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RamsTrackerAPI.Data;

#nullable disable

namespace RamsTrackerAPI.Migrations
{
    [DbContext(typeof(RamsDbContext))]
    [Migration("20240615194200_First migration")]
    partial class Firstmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RamsTrackerAPI.Models.Domain.MS", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MS_Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RAid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubcontractorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("revision")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RAid");

                    b.HasIndex("SubcontractorId");

                    b.ToTable("MS");
                });

            modelBuilder.Entity("RamsTrackerAPI.Models.Domain.RA", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DownloadUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("revision")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RA");
                });

            modelBuilder.Entity("RamsTrackerAPI.Models.Domain.Subcontractor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subcontractor");
                });

            modelBuilder.Entity("RamsTrackerAPI.Models.Domain.MS", b =>
                {
                    b.HasOne("RamsTrackerAPI.Models.Domain.RA", "RA")
                        .WithMany()
                        .HasForeignKey("RAid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RamsTrackerAPI.Models.Domain.Subcontractor", "Subcontractor")
                        .WithMany()
                        .HasForeignKey("SubcontractorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RA");

                    b.Navigation("Subcontractor");
                });
#pragma warning restore 612, 618
        }
    }
}
